census-ecosystem/opencensus-go-exporter-ocagent

v1/common.go
v1/example_test.go
v1/mock_agent_test.go
v1/nodeinfo.go
v1/ocagent.go
v1/ocagent_test.go
v1/options.go
v1/transform_spans.go
v1/transform_spans_test.go
v1/version.go

First cut at an agent exporter that can be
hooked into an OpenCensus library/application.
The exporter implements `trace.Exporter`
and it translates `go.opencensus.io/trace`.Span
instances into the agent's proto exchangable
Spans but also conforming to the agent's communication
protocol.

ocagent: v1 code started

---

README.md

The previous README looked blank without any
usage guide. This change copies the code in
the v1/example_test.go file to show an end-to-end
copy pastable example that anyone with an agent
can use.

README: add usage example

---

.travis.yml
load_test.go
ocagent.go

ocagent/ExportSpan: use size 1 instead of -1 in adding to bundler
The previous code used -1 which I had misinterpreted to mean
"unknown size" when adding elements to the bundler. However,
the correct usage is to be 1 which counts each spanData as
an entry and will trigger an upload when it hits the threshold.
Also added a regression test that is also a reproducer which makes
upto 50 simultaneous connections to the frontend server that then
generates many spans hence simulating load. However, the test is
for >=Go1.11 lest we have noisy output due to running out of file descriptors.
Fixes #13

ocagent/ExportSpan: use size 1 instead of -1 in adding to bundler

---

load_test.go
mock_agent_test.go
ocagent.go
ocagent_test.go
options.go
transform_spans_test.go

Fixes https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/22.

all: remove WithPort in favour of only using the WithAddress option

---

connection.go
load_test.go
ocagent.go
ocagent_test.go
options.go
transform_spans_test.go

Perform an indefinite background redial on failed connections
to ensure that this exporter can reconnect to the upstream
OpenCensus interceptor/agent.
This change allows environments that don't yet have the agent
deployed to start using this exporter and gradually roll-out
the agent. It helps trivial situations like an application
starting before the agent: of which it shouldn't crash
and fail to start running -- all the exported spans before
the agent is ready for connections, or at least if the
span buffer is full, will be discarded.
Added tests to ensure that this works and lock-in that
behavior.
Fixes #18

perform indefinite background reconnection attempts

---

ocagent.go

According to codes between [ocagent.go#L160](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/ocagent.go#L160) and [ocagent.go#L176](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/ocagent.go#L176), I think `traceSvcClient` in `Exporter` struct is useless. 
@odeke-em PTAL

fixup: remove useless traceSvcClient in Exporter struct

---

nodeinfo.go
ocagent.go
viewdata_to_metrics_test.go

This is the first step of piecemeal updates to allow
OpenCensus-Go to add metrics exporting before
https://github.com/census-instrumentation/opencensus-go#956
is resolved, as that issue is going to take a long time and
a lot of work.
After that, a follow-up change will be to then implement the
metrics service that will enable this exporter to
be an OpenCensus-Go stats+view exporter, then transform
that data into metricspb.Metric
Updates #31

metrics: OpenCensus-Go stats+view to Metrics converter

---

ocagent.go
transform_stats_to_metrics.go
viewdata_to_metrics_test.go

Following suit with the protocol, send a Resource as
the initial message since each application using ocagent
will create a single resource, just like we do with Node.
Fixes #17

trace, metrics: add Resource to every initial message

---

go.mod
ocagent.go
ocagent_test.go

In order to ensure that different nodes can be sent from the ocagent, a
new function was added that takes node information along with a batch of
spans.
Testing Done: unit test

Add batched span with node export functionality to oc exporter

---

ocagent.go
options.go
viewdata_to_metrics_test.go

Adds the ability to optionally compress gRPC requests via DefaultCallOptions.

Add compression option to oc exporter

---

ocagent.go
options.go

Adds the ability to send headers when first connecting to the TraceServiceClient stream

Add with headers option to agent exporter

---

ocagent.go

Currently we only send metadata (headers) on each export request, and not on the initial dial. If headers are used for routing or something authentication related, the initial connect won't be sent with headers, so it will fail.

Add headers to ClientConn dial

---

go.mod
go.sum
ocagent.go
ocagent_test.go
transform_stats_to_metrics.go
transform_stats_to_metrics_test.go
viewdata_to_metrics_test.go

Updated to OpenCensus-Proto v0.2.0 but also
ran `go mod tidy` too for a clean-up of old
resources.

go.mod: update to OpenCensus-Proto v0.2.0

---

transform_stats_to_metrics.go

due to https://github.com/census-instrumentation/opencensus-go/pull/1067, `go.opencensus.io/exemplar` doesn't exist any more.
this PR uses the new package

use new metricdata/exemplar

---

transform_stats_to_metrics.go

Fixes https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/52
Fixes https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/50
The refactoring with exemplar in core library has caused troubles in build, especially when go module is disabled. Remove all reference of exemplar for now.

Remove exemplar for now.

---

.travis.yml

Similar rationale to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/111.

Test against both module on and off in travis.

---

connection.go

The function setStateDisconnected() writes to the channel disconnectedCh, however, the function indefiniteBackgroundConnection() that reads the channel also calls setStateDisconnected(). If other routine already wrote to the channel between the time that indefiniteBackgroundConnection() read that channel and its call to setStateDisconnected() the background connection one gets blocked. The fix is just to attempt to write to the channel and proceed if it is already full (capacity is set to 1).

Avoid deadlock due to channel used for disconnect notification

---

example/main.go

Mostly from https://opencensus.io/exporters/supported-exporters/go/ocagent/, with adding zPages functionality.

 Add a runnable example of ocagent exporter.

---

ocagent.go
options.go

There are large number of grpc.DialOptions most of the time users don't need to specify them but when they are needed there is no way to do that. This change exposes all of them, whenever they conflict with settings already exposed by the agent the grpc.DialOption takes precedence by being set last.

Expose grpc.DialOption

---

connection.go

After an attempt to connect there is a wait before going back to the select that waits for disconnected state or closure of the stop channel, however, the wait doesn't check for the stop channel so the Stop can be delayed by connReattemptPeriod (plus any jitter).

indefiniteBackgroundConnection shouldn't hold Stop()

---

connection.go
ocagent.go

The changes here benefit most ExportTraceServiceRequest but can also be leveraged in other functions. Changes:
1. Record last error to so ExportTraceServiceRequest can return more information than simply “no active connection”, keeping track of the last connection error made the state kept in a field redundant and as such it was removed.
2. Attempt synchronous connect on Start: this came about in environments with high load where it may takes a long time until the go routine establishing the connection has a chance to run, in such scenario this best effort to connect at start minimizes chances of queueing and dropping at start.
3. In ExportTraceServiceRequest read errors after io.EOF for better reporting on the actual root cause. Notice that io.EOF itself is not considered an error per …

Record last connection error and attempt connection on Start()

---

ocagent.go
viewdata_to_metrics_test.go

This will be used when Agent sends proto metrics to Collector.
Also add proto resource to export requests.
Related to https://github.com/open-telemetry/opentelemetry-service/issues/231.
/cc @pjanotti

Add a method Exporter.ExportMetricsServiceRequest that accepts proto metrics

---

go.mod
mock_agent_test.go
ocagent.go
ocagent_test.go
resource_detector_test.go
viewdata_to_metrics_test.go

When WithResourceDetector option is used, make sure exporter uses ResourceDetector's detected resource when exporting traces and metrics.
Fixes #79

Ensure exporter respects ResourceDetector option

---

ocagent.go
options.go
transform_stats_to_metrics.go
transform_stats_to_metrics_test.go

In knative we need to set the component names(autoscaler and activator) as the prefix for metric names.  Both prometheus and stackdriver provide a way to do that:
https://github.com/census-ecosystem/opencensus-go-exporter-prometheus/blob/master/prometheus.go#L170
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/metrics_proto.go#L413
This PR brings the parity to opencensus agent.  
It's hard to test without a mock agent for metrics.  But I tested manually and it worked as expected.

Add an option to set metric name prefix

---

.travis.yml

This fixes #86 
Also skipped the install step which triggers travis_install_go_dependencies. This has reduced the build time almost by half as well.

Travis build fix and optimisation

---

example/main.go
ocagent.go
options.go
span_config.go
span_config_test.go
transform_spans.go

ocagent currently has default max annotations and events values which are not configurable. The annotations in the spans are dropped beyond this value.
opencensus-go provides option to configure span properties like MaxAnnotationEventsPerSpan, MaxMessageEventsPerSpan etc. When integrating opencensus-go with ocagent, opencensus-go provides ability to configure custom values but ocagent has default max values which results in annotations being dropped.
As part of this PR, the properties maxAnnotationEventsPerSpan and maxMessageEventsPerSpan are made configurable and falls back to default values when not specified.

Make max annotations and events per span configurable

---

ocagent.go
options.go

I discovered that our tests were taking about 2s per OpenCensus exporter created due to the defaults in `NewUnstartedExporter`. This PR allows reducing the defaults (for example, in test situations).

Add option to control metrics bundling
